/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewFAQ = IDL.Record({
  'question' : IDL.Text,
  'order' : IDL.Nat,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const FAQId = IDL.Nat;
export const NewTourPackage = IDL.Record({
  'title' : IDL.Text,
  'destination' : IDL.Text,
  'description' : IDL.Text,
  'price_inr_max' : IDL.Nat,
  'price_inr_min' : IDL.Nat,
  'highlights' : IDL.Vec(IDL.Text),
  'duration_days' : IDL.Nat,
  'best_season' : IDL.Text,
});
export const PackageId = IDL.Nat;
export const FAQ = IDL.Record({
  'id' : FAQId,
  'question' : IDL.Text,
  'order' : IDL.Nat,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const InquiryId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : InquiryId,
  'destination' : IDL.Text,
  'travel_dates' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const TourPackage = IDL.Record({
  'id' : PackageId,
  'title' : IDL.Text,
  'destination' : IDL.Text,
  'description' : IDL.Text,
  'price_inr_max' : IDL.Nat,
  'price_inr_min' : IDL.Nat,
  'highlights' : IDL.Vec(IDL.Text),
  'duration_days' : IDL.Nat,
  'best_season' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFAQ' : IDL.Func([NewFAQ], [FAQId], []),
  'addTourPackage' : IDL.Func([NewTourPackage], [PackageId], []),
  'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [InquiryId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewFAQ = IDL.Record({
    'question' : IDL.Text,
    'order' : IDL.Nat,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const FAQId = IDL.Nat;
  const NewTourPackage = IDL.Record({
    'title' : IDL.Text,
    'destination' : IDL.Text,
    'description' : IDL.Text,
    'price_inr_max' : IDL.Nat,
    'price_inr_min' : IDL.Nat,
    'highlights' : IDL.Vec(IDL.Text),
    'duration_days' : IDL.Nat,
    'best_season' : IDL.Text,
  });
  const PackageId = IDL.Nat;
  const FAQ = IDL.Record({
    'id' : FAQId,
    'question' : IDL.Text,
    'order' : IDL.Nat,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const InquiryId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : InquiryId,
    'destination' : IDL.Text,
    'travel_dates' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const TourPackage = IDL.Record({
    'id' : PackageId,
    'title' : IDL.Text,
    'destination' : IDL.Text,
    'description' : IDL.Text,
    'price_inr_max' : IDL.Nat,
    'price_inr_min' : IDL.Nat,
    'highlights' : IDL.Vec(IDL.Text),
    'duration_days' : IDL.Nat,
    'best_season' : IDL.Text,
  });
  
  return IDL.Service({
    'addFAQ' : IDL.Func([NewFAQ], [FAQId], []),
    'addTourPackage' : IDL.Func([NewTourPackage], [PackageId], []),
    'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [InquiryId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };