/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FAQ {
  'id' : FAQId,
  'question' : string,
  'order' : bigint,
  'answer' : string,
  'category' : string,
}
export type FAQId = bigint;
export interface Inquiry {
  'id' : InquiryId,
  'destination' : string,
  'travel_dates' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export type InquiryId = bigint;
export interface NewFAQ {
  'question' : string,
  'order' : bigint,
  'answer' : string,
  'category' : string,
}
export interface NewTourPackage {
  'title' : string,
  'destination' : string,
  'description' : string,
  'price_inr_max' : bigint,
  'price_inr_min' : bigint,
  'highlights' : Array<string>,
  'duration_days' : bigint,
  'best_season' : string,
}
export type PackageId = bigint;
export type Timestamp = bigint;
export interface TourPackage {
  'id' : PackageId,
  'title' : string,
  'destination' : string,
  'description' : string,
  'price_inr_max' : bigint,
  'price_inr_min' : bigint,
  'highlights' : Array<string>,
  'duration_days' : bigint,
  'best_season' : string,
}
export interface _SERVICE {
  'addFAQ' : ActorMethod<[NewFAQ], FAQId>,
  'addTourPackage' : ActorMethod<[NewTourPackage], PackageId>,
  'getFAQs' : ActorMethod<[], Array<FAQ>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getTourPackages' : ActorMethod<[], Array<TourPackage>>,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string, string],
    InquiryId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];