/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NewFAQ {
    question: string;
    order: bigint;
    answer: string;
    category: string;
}
export type Timestamp = bigint;
export type InquiryId = bigint;
export type FAQId = bigint;
export interface FAQ {
    id: FAQId;
    question: string;
    order: bigint;
    answer: string;
    category: string;
}
export type PackageId = bigint;
export interface NewTourPackage {
    title: string;
    destination: string;
    description: string;
    price_inr_max: bigint;
    price_inr_min: bigint;
    highlights: Array<string>;
    duration_days: bigint;
    best_season: string;
}
export interface TourPackage {
    id: PackageId;
    title: string;
    destination: string;
    description: string;
    price_inr_max: bigint;
    price_inr_min: bigint;
    highlights: Array<string>;
    duration_days: bigint;
    best_season: string;
}
export interface Inquiry {
    id: InquiryId;
    destination: string;
    travel_dates: string;
    name: string;
    email: string;
    message: string;
    timestamp: Timestamp;
    phone: string;
}
export interface backendInterface {
    addFAQ(faq: NewFAQ): Promise<FAQId>;
    addTourPackage(pkg: NewTourPackage): Promise<PackageId>;
    getFAQs(): Promise<Array<FAQ>>;
    getInquiries(): Promise<Array<Inquiry>>;
    getTourPackages(): Promise<Array<TourPackage>>;
    submitInquiry(name: string, email: string, phone: string, destination: string, travel_dates: string, message: string): Promise<InquiryId>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFAQ(arg0: NewFAQ): Promise<FAQId> {
        if (this.processError) {
            try {
                const result = await this.actor.addFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFAQ(arg0);
            return result;
        }
    }
    async addTourPackage(arg0: NewTourPackage): Promise<PackageId> {
        if (this.processError) {
            try {
                const result = await this.actor.addTourPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTourPackage(arg0);
            return result;
        }
    }
    async getFAQs(): Promise<Array<FAQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFAQs();
            return result;
        }
    }
    async getInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiries();
            return result;
        }
    }
    async getTourPackages(): Promise<Array<TourPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTourPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTourPackages();
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<InquiryId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
